### ISSUE TITLE
请问4块K20显卡跑了多久？

### ISSUE THREAD

**Issue by RuikangSun** [lzw-all-in/anime_person_translation#2]
我想用我的750ti一战

**Comment by lzw-all-in** [comment]
@RuikangSun  有点久了，但是我记得当时也就用了一两天，因为我把图片缩小到64x64了原来是128的。不过要注意显存够不够哦。减小batch size或者修改下图片的尺寸都行。

**Comment by lzw-all-in** [comment]
@RuikangSun 时间有点久了，但是我记得当时也就用了一两天，因为我把图片缩小到64x64了原来是128的。不过要注意显存够不够哦。减小batch size或者修改下图片的尺寸都行。

**Comment by RuikangSun** [comment]
Close old issues.
