### ISSUE TITLE
in self-attention.py why are you transpose beta?

### ISSUE THREAD

**Issue by Johnson-yue** [lzw-all-in/anime_person_translation#3]
Hi , in your [compute sa_feat](https://github.com/lzw-all-in/anime_person_translation/blob/da3d921d1086df5f10a0ce702ebacd0a0597e0a8/self_attention.py#L37) why are you transpose beta?

although the **beta** size is N-by-N but in original paper it is not necessary transpose
 only torch.bmm(h, beta) enough

is right?

**Comment by lzw-all-in** [comment]
@Johnson-yue  Hello I'm so glad to receive the advice from u. But this project has been unloaded 7 months ago . So maybe I'm not clear about the detail. But I just remember that I checked this sentence several times and I think it's right. Although the dimension is right whatever transpose or not but we must to make sure that the "right" row multiply the "right" column in torch.bmm.

**Comment by lzw-all-in** [comment]
@Johnson-yue Hello I'm so glad to receive the advice from u. But this project has been unloaded 7 months . So maybe I'm not clear about the detail. But I just remember that I checked this sentence several times and I think it's right. Although the dimension is right whatever transpose or not but we must to make sure that the "right" row multiply the "right" column in torch.bmm.

**Comment by lzw-all-in** [comment]
@Johnson-yue Hello I'm so glad to receive the advice from u. But this project has been unloaded 7 months . So maybe I'm not clear about the detail. But I just remember that I checked this sentence several times and I think it's right. Although the dimension is right whatever transpose or not but we must to make sure that the "right" row multiply the "right" column in torch.bmm.

If you still have some problems you can contact me again. : )

**Comment by Johnson-yue** [comment]
hi, I check SAGAN paper again, and I found your implement is right for v1 and I read is v2 paper and code.  I have no question about implement but,  did you get good performance with Self-attention layers?

I implemented v2 code but the performance was not good

**Comment by lzw-all-in** [comment]
Sorry, actually I haven't do experiments for a half year.  so sorry, I got a more urgent thing to do. Maybe when i finish it , i will come back. Your experiments is also about translate anime to person or something like style transfer ?

**Comment by Johnson-yue** [comment]
yes, my work  focuse on  domain transfer like person to anime,  cat to dog , domain 1 to domain 2

**Comment by lzw-all-in** [comment]
Got it ! Maybe I will be back at several months later. Can I ask you about the domain transfer knowledge ? THX : )

**Comment by Johnson-yue** [comment]
learn each other :）
